create TABLE IF NOT EXISTS requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id     BIGINT,
    requester_id BIGINT,
    created      TIMESTAMP WITHOUT TIME ZONE,
    status       VARCHAR(100)
);