spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**
        - id: request-service
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**,/users/*/events/*/requests/**
        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments/**,/events/*/comments/**,/comments/**,/admin/comments/**
        - id: event-service
          uri: lb://event-service
          predicates:
            - Path=/admin/**,/users/**,/events,/events/**,/categories,/categories/**,/compilations,/compilations/**
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,routes,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    gateway:
      enabled: true
    routes:
      enabled: true
    beans:
      enabled: true
    env:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    com.netflix.discovery: INFO